globalThis.TERM_DEFS = {
  "12-bar blues": "The foundational harmonic structure of blues music — a repeating 12-bar chord progression typically using chords I, IV, and V. Serves as the backbone for countless blues, rock, and jazz songs.",
  "4 to the floor": "A kick on every beat of the bar: 1, 2, 3, 4.",
  "808": "The Roland TR-808 drum machine (1980). Its booming, pitch-tunable kick drum and synthetic handclaps became definitive sounds of hip-hop, trap, and electronic music.",
  "808 bass": "A deep electronic sub-bass sound associated with the Roland TR-808 lineage.",
  "808 kick": "A punchy electronic kick associated with the Roland TR-808 lineage.",
  "909": "The Roland TR-909 drum machine (1983). Its crisp snare and punchy kick became central to house, techno, and dance music production worldwide.",
  "a cappella": "Singing or vocal performance with no instrumental accompaniment — voice only.",
  "aching": "A sustained, dull emotional pain.",
  "acid bass": "A squelchy, filter-swept bass sound produced by the Roland TB-303 bass synthesiser. Defined acid house music in the late 1980s and remains a staple of electronic genres.",
  "ad-lib": "An improvised vocal line or phrase added spontaneously over the main performance, often used in R&B and hip-hop to fill space or add personality.",
  "aggressive": "Forceful, confrontational, in-your-face energy.",
  "airy": "Light and open, with breathy or spacious upper detail.",
  "anthemic": "Large-scale and communal; designed to be felt collectively.",
  "arco": "String performance technique where the bow is used on the strings, producing a sustained, singing tone. The opposite of pizzicato (plucking).",
  "arpeggiated bass synth": "A bass synth playing chord notes one after another instead of together.",
  "arpeggiated strings": "Strings outlining chord tones in sequence rather than as a block.",
  "arpeggio": "The notes of a chord played in sequence rather than simultaneously — one after another, ascending or descending. A common melodic and keyboard pattern.",
  "backbeat": "Emphasis on beats 2 and 4 in a 4/4 bar — the beats where the snare typically lands in rock, pop, and funk. The snap of the snare on the backbeat is one of the most recognisable elements of popular music.",
  "balladic": "In the style of a ballad; slow, direct, and emotionally led.",
  "bedroom": "An intimate, lo-fi, often home-recorded production character.",
  "bedroom pop": "A genre and aesthetic of music recorded at home — intimate, lo-fi, and DIY in character. Defined by soft vocals, simple arrangements, and the sound of domestic recording rather than professional studios.",
  "bittersweet": "Simultaneously painful and pleasurable; joy undercut by sadness.",
  "blues": "Rooted in blues language or feeling, often expressive and bent in tone.",
  "blues shuffle": "A swung triplet-based groove central to many blues feels.",
  "bongos": "A pair of small, attached single-headed drums played between the knees with the fingers. Produce a high, bright, expressive tone — used in Afro-Cuban, Latin, and jazz-influenced music.",
  "bouncy": "Playfully energetic, spring-loaded rhythm.",
  "bridge": "A contrasting section of a song that provides relief from the verse–chorus pattern. Usually appears once, offering a new perspective melodically, lyrically, or harmonically before returning to the chorus.",
  "bright": "Treble-present and clear, with forward upper frequencies.",
  "brooding": "Dark, heavy introspection; emotionally weighted.",
  "brushed drums": "Drums played with brushes, producing a soft swishing texture.",
  "brushes": "Wire or nylon fan-shaped sticks used to play the drum kit more softly. Produce a swishing, hushed sound — essential in jazz ballads, bossa nova, and quiet acoustic settings.",
  "build-up": "A section that gradually increases energy, tension, or density — typically leading into a drop or chorus. Common in electronic music.",
  "cajon": "A box-shaped percussion instrument of Peruvian origin, played by slapping the front face. Produces a warm bass thud and crisp snare-like crack, popular in acoustic and flamenco settings.",
  "call and response": "A musical conversation between two phrases or performers, where one phrase (the call) is answered by another (the response). Deeply rooted in African, gospel, and blues traditions.",
  "carnival": "Festive, exuberant, and often brassy or fairground-like.",
  "cathartic": "Releasing pent-up emotion; purging through expression.",
  "celebratory": "Festive and marked by joy, release, or achievement.",
  "chunky": "Thick and blocky in texture, with weighty attacks.",
  "cinematic": "Scene-setting in scale or drama, as though supporting a visual narrative.",
  "clave": "A fundamental rhythmic pattern in Afro-Cuban and Latin music, typically two bars of 3+2 or 2+3. It acts as the rhythmic spine around which all other parts are organised.",
  "claves": "Two cylindrical hardwood sticks struck together to produce the clave rhythm — a clear, penetrating click central to Latin music.",
  "clavinet": "An electro-acoustic keyboard instrument (Hohner) that sounds like an amplified clavichord — percussive, funky, and bright. Stevie Wonder's 'Superstition' is the defining example.",
  "coda": "A concluding passage that brings a piece to a close, often after the main structure has ended. From Italian for 'tail'.",
  "comping": "Short for 'accompanying' — the rhythmically varied, supportive chord playing typically done by piano or guitar in jazz and soul. Comping leaves space for soloists and other voices.",
  "confessional": "Intimate and personal, as if revealing private truths.",
  "congas": "Tall, narrow single-headed drums of Afro-Cuban origin, played with the hands. Available in different sizes (quinto, conga, tumba) and fundamental to Latin, jazz, and funk grooves.",
  "crisp": "Clean and sharply defined at the edges.",
  "cross-stick": "A snare drum technique where the stick tip rests on the drumhead while the shaft clicks against the rim — producing a dry, woody 'tock' sound. Common in ballads and bossa nova.",
  "crunchy": "Rough-edged and gritty, often with saturated bite.",
  "dance-ready": "BPM, groove and energy aligned for the dancefloor.",
  "dark": "Reduced in upper frequencies, with a heavier or shadowed tone.",
  "defiant": "Boldly resistant or oppositional in character.",
  "defiantly": "In a boldly resistant or oppositional way.",
  "demo quality": "Deliberately rough or unpolished sound that resembles an early demo recording — raw, unprocessed, and lacking studio polish. Sometimes used intentionally for authenticity.",
  "dense": "Packed with sonic information and little empty space.",
  "depressing": "Heavy or hopeless; emotionally oppressive.",
  "desperate": "Urgent, extreme need; last-resort emotion.",
  "devotional": "Reverent, worshipful, and deeply committed.",
  "dirty": "Roughened, noisy, or deliberately imperfect in tone.",
  "dissociated": "Detached or distant from self or reality.",
  "dizzy": "Unsteady, spinning, or overloaded in feel.",
  "dizzying": "So intense or spinning that it feels disorienting.",
  "double tracked": "A recording technique where a performer records the same part twice and both takes are layered together. Creates a naturally thicker, wider sound — especially used on vocals and guitars.",
  "downbeat": "Beat 1 of a bar — the primary, strongest point of rhythmic emphasis in most Western music. The conductor's baton comes down on the downbeat.",
  "dramatic": "Heightened, theatrical emotional scale.",
  "dreamy": "Soft-focused, hazy, and floating in mood.",
  "drop": "The moment in electronic music where the build-up resolves into the main beat — often with a sudden surge of bass and rhythm. A defining structural moment in house, EDM, and trap.",
  "drum machine": "An electronic device that generates and sequences drum sounds — either sampled or synthesised. Ranges from vintage hardware (808, 909) to modern software equivalents.",
  "EDM drums": "Drum sounds and patterns typical of Electronic Dance Music — characterised by heavy kick drums, crisp snares, rapid hi-hats, and programmed percussion designed for dancefloor impact.",
  "eerie": "Unsettlingly strange; uneasy without becoming overtly threatening.",
  "elated": "Lifted, exhilarated, and intensely happy.",
  "ethereal": "Delicate, celestial, and barely-there.",
  "euphoric": "An intense emotional high or peak elation.",
  "expansive": "Wide, open, and spreading outward in space or scale.",
  "explosive": "Sudden and forceful, with a sharp release of energy.",
  "falsetto": "A vocal register above the normal chest voice, produced by using the head rather than chest resonance. Creates a lighter, often breathy tone — used widely in R&B, pop, and soul.",
  "fat": "Full and heavy, with strong low-mid body.",
  "feral": "Raw, primal, uncivilised energy.",
  "festive": "Celebratory, lively, and socially energised.",
  "field recording": "Audio captured in a real-world environment outside a studio — ambience, nature, crowds, machinery. Used as texture, mood-setting background, or raw material for sampling.",
  "filter modulated": "A sound whose filter (the control over frequency content) is being automatically changed over time, often by an LFO. Creates a sweeping, wah-like, or pulsing timbral movement.",
  "fingerpicking": "A guitar technique where individual strings are plucked with the fingertips or fingernails (rather than a plectrum), allowing independent melody, bass, and inner voice lines to be played simultaneously.",
  "flanger": "A modulation effect that mixes a signal with a slightly time-delayed copy of itself, sweeping that delay up and down. Produces a whooshing, jet-plane-like sound.",
  "floating": "Weightless and unanchored; drifting through space.",
  "floor tom": "The large, low-pitched tom-tom drum that stands on its own legs to the right of a drum kit. Produces a deep, resonant thud — often used in drum fills.",
  "focus": "The main centre of attention or the element being highlighted.",
  "focused": "Tightly concentrated and clearly directed.",
  "four on the floor": "A kick drum pattern where the bass drum hits on every beat (1, 2, 3, 4) of a 4/4 bar. The rhythmic engine of disco, house, and most electronic dance music.",
  "fragile": "A delicate emotional state; easily broken or overwhelmed.",
  "frenzied": "Wild, uncontrolled, chaotic intensity.",
  "fretless bass": "An electric bass guitar without frets on the neck. Allows smooth gliding between notes (portamento) and a warm, vocal tone — associated with jazz fusion and soul.",
  "gated reverb": "A reverb effect that is abruptly cut off by a noise gate before it naturally decays, creating a short, explosive burst of space. Iconic in 1980s pop and rock — most famously associated with Phil Collins' drum sound.",
  "gentle": "Soft, careful, and low-impact in feel.",
  "gently": "In a soft, careful, low-impact way.",
  "ghostly": "Thin, spectral, and barely present.",
  "glassy": "Smooth, transparent, and reflective in texture.",
  "guajeo": "A syncopated piano or guitar ostinato pattern in Cuban and Latin music — a repeating melodic-rhythmic figure that weaves around the clave. Also the basis of the montuno.",
  "half-time beat": "A drum pattern that feels twice as slow as the underlying tempo by placing the snare on beat 3 instead of 2 and 4 — creating a heavier, more spacious feel popular in hip-hop and trap.",
  "hard-hitting": "Impactful, physically forceful sound or emotion.",
  "harsh": "Abrasive or piercing, especially in the upper mids or highs.",
  "haunted": "Marked by persistent, unresolved emotion or memory.",
  "head": "In jazz, the 'head' is the main melody or theme of a tune — played at the opening and closing of a performance, with improvised solos in between.",
  "hi-fi": "High fidelity — audio that is clean, full-range, and accurately reproduced with minimal noise or distortion. The opposite of lo-fi.",
  "hi-hat": "Two cymbals mounted on a stand that can be opened and closed by a foot pedal, or struck with a stick. The hi-hat defines rhythmic pulse and feel — closed for tight patterns, open for wash and groove.",
  "high frequency": "Occupying the upper spectral range; treble-focused.",
  "hook": "The most memorable, catchy part of a song — the musical idea that hooks the listener. Often the chorus or a key melodic phrase that the whole song orbits around.",
  "hopeful": "Anticipating positive outcomes; optimistic energy.",
  "hypnotic": "Repetitive and trance-inducing; draws the listener in.",
  "immersive": "An enveloping sonic environment that surrounds the listener.",
  "infectious": "Irresistibly fun; provokes involuntary movement.",
  "intense": "Concentrated, forceful, and high-pressure in feel.",
  "interlude": "A short passage between main sections of a song — often instrumental, providing a moment of transition, reflection, or contrast.",
  "intimate": "Close, personal, and inwardly scaled.",
  "intimately": "In a close, personal, inwardly scaled way.",
  "intricate": "Detailed and finely worked, with many small internal parts.",
  "jolt": "A sharp shock or abrupt burst of force.",
  "jolting": "Sharp, sudden, and startling in impact.",
  "joyous": "Full, open, and unrestrained happiness.",
  "juicy": "Rich, saturated, and pleasingly full in tone.",
  "kick": "The bass drum of a drum kit, played with a foot pedal. Provides the low-frequency punch and rhythmic foundation of most popular music.",
  "legato": "Notes played smoothly and connected, with no gaps between them. The opposite of staccato. Creates a flowing, continuous feel.",
  "LFO": "Low Frequency Oscillator — a modulation source in synthesis that cycles below audible range (typically 0.1-20Hz), used to automatically modulate parameters like pitch (vibrato), filter (wobble), or volume (tremolo) over time.",
  "lilting": "Light, rhythmically buoyant; a gentle rise-and-fall.",
  "live room recording": "Audio captured with musicians performing together in the same room, with natural acoustic bleed between instruments. Gives recordings an organic, together feel distinct from isolated studio tracking.",
  "lo-fi": "Low fidelity — audio with audible imperfections: tape hiss, vinyl crackle, reduced frequency range, or distortion. Used intentionally for warmth, nostalgia, or character.",
  "locked-in": "Extremely tight rhythmic cohesion between elements.",
  "longing": "An intense, aching desire for something absent.",
  "loud": "High in force or volume; prominent and direct.",
  "loudly": "In a forceful, prominent way.",
  "low frequency": "Occupying the lower spectral range; bass-focused.",
  "meditative": "Still, inward, and contemplative in mood.",
  "meditatively": "In a still, inward, contemplative way.",
  "melancholic": "A deep, lingering sadness with a reflective quality.",
  "melisma": "A vocal technique where a single syllable is sung across multiple notes in a rapid, ornamented run. Central to gospel, R&B, and soul singing — famously associated with artists like Whitney Houston.",
  "mellotron": "A keyboard instrument that plays back pre-recorded magnetic tape loops of real instruments (strings, flutes, choir). Its warm but slightly unstable sound defined psychedelic and progressive rock in the 1960s-70s.",
  "menacing": "Explicitly threatening; danger implied.",
  "mid frequency": "Occupying the middle spectral range; presence-focused.",
  "middle eight": "A bridge section (often literally eight bars) that contrasts with the verse and chorus — providing melodic and harmonic relief before the final chorus. Common in British songwriting tradition.",
  "militant": "Marching, disciplined, combative energy.",
  "mono recording": "Audio captured as a single channel — no stereo width or left/right separation. Gives a focused, direct sound. Common in vintage recordings and used intentionally for certain elements.",
  "montuno": "A repeating syncopated piano pattern in Afro-Cuban and salsa music, built on the clave rhythm. Similar to a guajeo but typically simpler — the rhythmic-harmonic engine of salsa.",
  "motorik": "A hypnotic, metronomic drum pattern at a steady mid-tempo pulse — associated with German Krautrock bands like Can and Neu!. Characterised by an unwavering, driving hi-hat and minimal variation.",
  "mournful": "Expressing deep grief or sorrow.",
  "murky": "Clouded or muddy, with reduced clarity.",
  "mystical": "Sacred, ancient, or spiritually evocative.",
  "nasty": "Deliberately abrasive, ugly, or mean in tone.",
  "obsessive": "Fixated, looping emotional intensity.",
  "off-beat": "Rhythmic emphasis placed between the main beats — the 'ands' in a bar of 4/4 (e.g., 1-and-2-and-3-and-4). Playing on the off-beat creates syncopation, lightness, or groove.",
  "open hi-hat": "A hi-hat struck while the two cymbals are apart, producing a sustained, washy crash sound. Contrasts with the tight 'chick' of a closed hi-hat and often marks phrase-end accents.",
  "otherworldly": "Beyond familiar reality; alien or supernatural in tone.",
  "overdrive": "A mild to moderate form of harmonic distortion that simulates the natural breakup of a valve amplifier when pushed hard. Warmer and more musical than heavy distortion.",
  "paranoid": "Anxious suspicion; feeling watched or threatened.",
  "pedal note": "A sustained or repeated note (usually in the bass) that is held while harmonies change above it. Creates tension when the harmony moves away from the pedal, and resolution when it returns.",
  "phaser": "A modulation effect that splits a signal and shifts the phase of one copy, creating sweeping peaks and notches in the frequency spectrum. Produces a swirling, swooshing sound.",
  "pizzicato strings": "A string technique where the strings are plucked with the finger rather than bowed. Produces a short, percussive tone — contrasts with the sustained arco sound.",
  "plate reverb": "Reverb created by suspending a large metal plate and using transducers to vibrate it. Produces a bright, dense, smooth reverb — the classic vocal and snare reverb of studio recordings.",
  "playful": "Light, mischievous, and openly exploratory.",
  "playfully": "In a light, mischievous, exploratory way.",
  "polyrhythm": "Two or more conflicting rhythmic patterns played simultaneously — for example, three beats against four, or five against two. Creates complex, layered groove.",
  "pre-chorus": "A section between the verse and chorus that builds anticipation and transitions energy upward before the chorus arrives. Also called a 'lift' or 'climb'.",
  "programmed drums": "Drum parts created using software or hardware drum machines rather than recorded live. Allows precise timing, editing, and use of sampled or synthesised sounds.",
  "psychadelic": "Swirling, expansive, or altered-state sonics.",
  "pull": "A slight backward lean or drag against the pulse; can also describe energy drawing inward.",
  "pulling": "Leaning backward against the beat or drawing the energy inward.",
  "pulsing": "A steady, repetitive beat driving forward momentum.",
  "push": "A forward-driving pressure in timing or energy.",
  "pushing": "Actively driving ahead in timing or energy.",
  "quiet": "Low in volume or intensity; subdued.",
  "quietly": "In a subdued, low-volume way.",
  "radiant": "Glowing and outwardly energised.",
  "radio effect": "Audio processing that mimics the narrow bandwidth and mild distortion of AM radio. Creates a vintage or broadcast character, similar to but broader than the telephone effect.",
  "reflective": "Thoughtful and inward-looking; quietly contemplative.",
  "refrain": "A repeating line or phrase — often at the end of each verse — that acts as a summarising lyrical and melodic anchor. Sometimes used interchangeably with 'chorus', though technically shorter.",
  "resigned": "Quiet acceptance of something difficult, without struggle.",
  "restless": "Unable to settle; agitated energy seeking release.",
  "restrained": "Held back and controlled rather than fully released.",
  "rhodes": "The Fender Rhodes electric piano — a keyboard instrument using metal tines struck by hammers, producing a warm, bell-like tone with a characteristic bloom. A cornerstone of soul, jazz, and funk.",
  "ride cymbal": "A large cymbal played with a stick to keep a steady rhythmic pattern, particularly in jazz. Has a clear, sustained 'ping' at the bow and a washy sound on the bell.",
  "rimshot": "Striking the drum rim and head simultaneously, producing a loud, sharp 'crack'. Used for accents, backbeats, and dramatic emphasis.",
  "riser": "A sound effect that builds in pitch and/or volume over a period of time, creating tension and anticipation before a drop or chorus. Common in electronic and pop production.",
  "rolling": "Continuous flowing movement, like waves.",
  "sawtooth": "A synthesiser waveform that looks like a ramp — rich in harmonics and spectrally bright. Forms the basis of many classic synth lead and bass sounds.",
  "sentimental": "Tender emotion tied to memory or nostalgia.",
  "sequencer": "A device or software that records and plays back a sequence of musical events (notes, rhythms, control changes) in a repeating pattern. From early hardware step sequencers to modern DAW MIDI.",
  "sexy": "Sensual, suggestive, and physically charged.",
  "shimmer": "A soft, radiant sparkle in the upper range.",
  "shimmering": "Glowing with fine, sparkling upper detail.",
  "shout": "A forceful, projected vocal or emotional burst.",
  "shouting": "Delivered with forceful projection or heightened emotional release.",
  "sidechain": "A routing technique where one audio signal controls the processing of another. Most famously used to have the kick drum trigger compression on the bass or synth pads, creating the 'pumping' effect in electronic music.",
  "sine wave": "The purest synthesiser waveform — a smooth, single-frequency tone with no harmonics. Sounds clean and soft; often used for sub bass or subtle harmonic reinforcement.",
  "sinister": "Darkly threatening; a malevolent undertone.",
  "slap bass": "An electric bass technique where the thumb strikes the string percussively (slap) and the finger pulls and snaps the string against the fretboard (pop). Creates a bright, punchy, rhythmically aggressive sound central to funk.",
  "slinky": "Smooth, flexible, and lightly sinuous in motion or feel.",
  "smooth": "Even and polished, without abrasive edges.",
  "soft": "Low in force or volume; gentle rather than forceful.",
  "softly": "With low force or volume; delivered gently.",
  "solemn": "Serious, grave, and ceremonial in mood.",
  "solemnly": "In a serious, grave, ceremonial way.",
  "soothing": "Calming and tension-reducing.",
  "soundtrack": "A scene-setting or narrative-supporting feel, like music for picture.",
  "spacious": "A wide-open sonic space with room to breathe.",
  "spring reverb": "Reverb created by running a signal through a physical metal spring. Produces a bouncy, twangy, lo-fi reverb character — iconic in surf music, dub, and vintage country.",
  "square wave": "A synthesiser waveform that alternates sharply between two values. Has a hollow, reedy quality — rich in odd harmonics. Forms the basis of many classic synth bass and woodwind-like sounds.",
  "staccato": "Notes played short and detached, with space between each. The opposite of legato. Creates a clipped, percussive character.",
  "straining": "Pushing against limits; effortful and taut.",
  "sub bass": "Bass frequencies below roughly 80Hz — felt more than heard on most speakers, especially on large systems. Provides physical weight and low-end power, often generated by a sine wave or sub oscillator.",
  "sub drop": "A sudden burst of ultra-low sub bass — often pitched downward — used at the moment of a drop for maximum physical impact on a sound system.",
  "surreal": "Strange, dreamlike, and logic-defying.",
  "suspended": "Held in tension; resolution withheld.",
  "swaying": "Gentle side-to-side rhythmic movement.",
  "sweet": "Pleasing, uncomplicated, and openly positive.",
  "swell": "A gradual rise in level, size, or emotional force.",
  "swelling": "Growing gradually in level, size, or emotional force.",
  "swing": "A rhythmic feel where pairs of notes are played unevenly — the first note longer, the second shorter — giving music a lilting, shuffling, or jazz-influenced groove. Contrasts with straight (even) timing.",
  "swinging": "A jazz-inflected rhythmic feel, leaning into triplet motion.",
  "syncopation": "Placing rhythmic emphasis on normally weak or in-between beats, creating a feeling of rhythmic displacement or surprise. A key element of funk, jazz, Latin, and almost all popular music groove.",
  "talkbox": "A device that sends guitar or synth audio through a plastic tube into the performer's mouth, allowing them to shape the sound with their lips and tongue to produce speech-like effects. Made famous by Peter Frampton and Roger Troutman.",
  "tape delay": "An echo effect that uses a magnetic tape loop to record and play back a signal with a time delay. Produces a warm, slightly degraded echo that softens with each repeat — characteristic of vintage recordings.",
  "tape hiss": "The continuous high-frequency noise inherent in analogue magnetic tape recordings. Used intentionally in lo-fi production to evoke warmth, age, or a vintage aesthetic.",
  "telephone effect": "Audio processing that mimics the narrow frequency range and distortion of a telephone call — creating a thin, distant, or lo-fi vocal or instrument sound.",
  "tender": "Soft emotional care; delicate affection.",
  "timbales": "A pair of shallow, single-headed metal-shell drums on a stand, played with sticks. Central to salsa, Latin jazz, and Cuban music — producing a bright, sharp attack distinct from standard tom-toms.",
  "trance-like": "Repetitive and hypnotic; inducing a meditative or altered state.",
  "tremolo": "A rapid, regular variation in volume — creating a pulsing, undulating effect. Common in guitar amplifiers and Rhodes pianos. Often confused with vibrato (pitch variation).",
  "triumphant": "Carrying a sense of victory, achievement, or overcoming.",
  "turnaround": "A short harmonic phrase at the end of a section (typically 2 or 4 bars) that leads back to the start of the progression. Essential in blues and jazz — sets up the cycle to begin again.",
  "twinkle": "A light, sparkling flicker in the upper range.",
  "twinkling": "Flickering with light, sparkling upper-range detail.",
  "uneasy": "Low-level discomfort; something feels off.",
  "urgent": "Pressing, immediate, and difficult to ignore.",
  "vamp": "A repeating harmonic or rhythmic figure that is played continuously — holding a section in place while a soloist plays, a vocalist improvises, or as an intro/outro device.",
  "vibrato": "A rapid, regular variation in pitch — creating a warm, expressive wavering effect. Used by singers, string players, and guitarists to add emotion and sustain to held notes.",
  "vinyl crackle": "The distinctive crackling and popping noise produced by dust and imperfections on a vinyl record. Used intentionally in lo-fi and hip-hop production to evoke nostalgia and warmth.",
  "vocal run": "A rapid ornamental passage across multiple notes sung on a single syllable — similar to melisma. Central to gospel, R&B, and soul vocal technique.",
  "vocoder": "A device that analyses the formant structure of a voice and applies it to a synthesised tone, creating robotic, harmonised vocal sounds. Widely used in electronic, funk, and pop music.",
  "volatile": "Unpredictable, liable to explode; unstable energy.",
  "vulnerable": "Emotionally exposed, open, and unguarded.",
  "wah pedal": "A guitar effect pedal controlled by a rocker mechanism that sweeps a filter up and down the frequency spectrum — producing a vowel-like 'wah' sound. Central to funk and psychedelic rock.",
  "walking bass": "A bass line that moves smoothly from note to note in a steady rhythm (typically quarter notes), outlining the harmony and keeping continuous forward motion. The backbone of jazz and upright bass playing.",
  "wall of sound": "A production technique (pioneered by Phil Spector) that layers many instruments and voices together into a dense, thick, reverberant mass of sound that fills all available space.",
  "warm": "Rounded, inviting, and rich in lower-mid tone.",
  "weight": "A sense of physical or emotional heaviness; gravitas.",
  "wistful": "A gentle, pensive longing for something past or out of reach.",
  "wobble bass": "A bass synth sound with a rhythmically modulated filter, creating a pulsing, wavering low-end — central to dubstep and bass music. The rate of the wobble is typically synced to the tempo.",
  "wobbly": "Unsteady or undulating, often with pitch or modulation movement.",
  "worship": "A devotional or congregational feel common in worship music.",
  "wurlitzer": "The Wurlitzer electric piano — a keyboard instrument with metal reeds struck by rubber hammers. Has a slightly buzzy, nasal, intimate character distinct from the Rhodes. Widely used in soul and funk.",
  "yearning": "A persistent emotional pull toward something unattainable."
};
